# 本番用

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# 接続切れ対策
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hilari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000