# 本番用

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# 接続タイムアウト設定
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.maximum-pool-size=5